#!/usr/bin/bash

# script to generate the params.sv file based on the command line parameters
# usage: ./genParams2 [OUTW] [DEPTH] [WR_EN_PROB] [TREADY_PROB]
#    where you will replace [OUTW] [DEPTH] [WR_EN_PROB] nad [TREADY_PROB]
#    with the desired value of those parameters.
#    Remember, if WR_EN_PROB or TREADY_PROB are 0, the simulator will randomize them.
# example: for OUTW=32, DEPTH=33, with random WR_EN_PROB and TREADY_PROB
#         run: ./genParams2 32 33 0 0 

if [ $# -ne 4 ]; then
    echo "ERROR: incorrect number of parameters given."
    echo "Usage: ./genParams2 [OUTW] [DEPTH] [WR_EN_PROB] [TREADY_PROB]"
    echo "See comments in genParams2 file for more information"
else
    echo "\`define OUTWVAL $1" > params.sv
    echo "\`define DEPTHVAL $2" >> params.sv
    echo "\`define WRENPR $( sed 's/^[.]/0./' <<< "$3" )" >> params.sv
    echo "\`define TRPR $( sed 's/^[.]/0./' <<< "$4" )" >> params.sv
fi