#!/usr/bin/bash

# script to generate the params.sv file based on the command line parameters, 
# compile the code and testbench, and run simulation.
# usage: ./simParams2 [OUTW] [DEPTH] [WR_EN_PROB] [TREADY_PROB] [GUI]
#    where you will replace [OUTW] [DEPTH] [WR_EN_PROB] nad [TREADY_PROB]
#    with the desired value of those parameters.
#    Remember, if WR_EN_PROB or TREADY_PROB are 0, the simulator will randomize them

#    if [GUI] is 0, the simulation will run in waveform mode. If [GUI] is 1, it will 
#    run QuestaSim in GUI mode
# example: for OUTW=32, DEPTH=33, with random WR_EN_PROB and TREADY_PROB,
#          simulating at the command line only, run: 
#              ./simParams2 32 33 0 0 0

# If you want to run in GUI mode, you should run with & at the end, like
#        ./simParams2 32 33 0 0 1 &

# Note that this will compile all .sv files in your directory. If instead you
# only want to compile some of them, you can edit this or compile directly from the command line.

if [ $# -ne 5 ]; then
    echo "ERROR: incorrect number of parameters given."
    echo "Usage: ./simParams2 [OUTW] [DEPTH] [WR_EN_PROB] [TREADY_PROB] [GUI]"
    echo "See comments in simParams2 file for more information"
else
    ./genParams2 $1 $2 $3 $4
    vlog -64 +acc *.sv 
    if [[ $5 -eq 0 ]]; then
        vsim -64 -sv_seed random -c fifo_out_tb -do "run -all; quit"
    else 
        vsim -64 -sv_seed random fifo_out_tb
    fi
fi